version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: admin
      POSTGRES_DB: demo
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ 

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 9090:8080

  book-service:
    image: rich0423/book-service:1.0
    depends_on:
      - db
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/demo
      - JAVA_ENABLE_DEBUG=true
    restart: always
    ports:
      - 9091:8080
      - 5005:5005

volumes:
  database-data: