version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: admin
      POSTGRES_DB: demo
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ 

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

volumes:
  database-data: